# Generated by Django 4.2.16 on 2024-09-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0002_collection_created_at_collection_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='uuid',
            new_name='collection_uuid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='uuid',
            new_name='movie_uuid',
        ),
    ]
