# Generated by Django 4.2.16 on 2024-09-22 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movie_collection.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_collection', '0003_rename_uuid_collection_collection_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=movie_collection.models.get_request_id, max_length=255, unique=True)),
                ('user', models.IntegerField(db_index=True, default=0, null=True)),
                ('method', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(db_index=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('headers', models.TextField(null=True)),
                ('response_status', models.CharField(max_length=255, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('query_params', models.JSONField(null=True)),
                ('ip_address', models.CharField(max_length=42)),
                ('cookies', models.JSONField(null=True)),
                ('request_date', models.DateField(blank=True, db_index=True, null=True)),
                ('execution_time', models.DurationField(null=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=100, null=True)),
                ('query_count', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'requests_tracking',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('title', 'user')},
        ),
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_collection.collection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_collection.movie')),
            ],
            options={
                'db_table': 'movie_collection',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collections', through='movie_collection.MovieCollection', to='movie_collection.movie'),
        ),
    ]
