# Generated by Django 4.2.16 on 2024-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0004_requestdata_remove_movie_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_success',
            field=models.BooleanField(default=True),
        ),
    ]
