# Generated by Django 4.2.16 on 2024-09-22 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0005_collection_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
