# Generated by Django 4.2.16 on 2024-09-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0006_alter_collection_collection_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_uuid',
            new_name='uuid',
        ),
    ]
