# Generated by Django 4.2.16 on 2024-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0007_rename_movie_uuid_movie_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='request_type',
            field=models.CharField(blank=True, max_length=255, null=-1),
            preserve_default=-1,
        ),
    ]
